# Generated by Django 5.2.6 on 2026-03-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postimage_remove_postimages_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='OG Image URL'),
        ),
    ]
