# Generated by Django 5.2.6 on 2026-03-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='og_image_file',
            field=models.ImageField(blank=True, help_text='Locally cached copy of the OG image', null=True, upload_to='og_images/'),
        ),
    ]
