# Generated by Django 5.2.6 on 2026-03-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_og_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='og_image_file',
        ),
    ]
