# Generated by Django 5.2.6 on 2026-03-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_view_count_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
