# Generated by Django 5.2.6 on 2026-03-09 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_tags'),
        ('stages', '0010_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', 'is_blocked'], name='posts_post_is_publ_f3a97e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['stage', 'is_published', 'is_blocked', '-created_at'], name='posts_post_stage_i_636d86_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'is_published', '-created_at'], name='posts_post_author__0dec80_idx'),
        ),
    ]
