# Generated by Django 5.2.6 on 2026-03-09 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user'], name='posts_bookm_user_id_832cae_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['post'], name='posts_bookm_post_id_4cac26_idx'),
        ),
        migrations.AddIndex(
            model_name='dislike',
            index=models.Index(fields=['post'], name='posts_disli_post_id_0ffa78_idx'),
        ),
        migrations.AddIndex(
            model_name='dislike',
            index=models.Index(fields=['user', 'post'], name='posts_disli_user_id_9f7515_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post'], name='posts_like_post_id_db9889_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'post'], name='posts_like_user_id_88178d_idx'),
        ),
    ]
