# Generated by Django 4.1.1 on 2022-11-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
