# Generated by Django 4.1.1 on 2022-11-27 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_national_id_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
