# Generated by Django 4.1.1 on 2022-12-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_alter_stage_name'),
        ('users', '0003_user_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jusers', to='stages.stage'),
        ),
    ]
