# Generated by Django 4.2.2 on 2023-06-15 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_views',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
