# Generated by Django 5.2.6 on 2026-03-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, help_text='Profile banner image', null=True, upload_to='banners/'),
        ),
    ]
