# Generated by Django 5.2.6 on 2026-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_time_online',
            field=models.PositiveIntegerField(default=0, help_text='Total seconds spent online'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Post Liked'), ('comment', 'New Comment'), ('reply', 'Comment Reply'), ('follow', 'New Follower'), ('message', 'New Message'), ('mention', 'Mentioned'), ('mod_add', 'Added as Moderator'), ('mod_remove', 'Removed as Moderator'), ('stage_ban', 'Stage Banned'), ('stage_unban', 'Stage Unbanned'), ('post_removed', 'Post Removed by Mod'), ('mod_warn', 'Warning from Moderator')], max_length=20),
        ),
    ]
