# Generated by Django 5.2.6 on 2026-03-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_add_message_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
    ]
