# Generated by Django 5.2.6 on 2026-03-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0014_seed_new_stages'),
        ('users', '0024_add_performance_indexes_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_interests',
            field=models.ManyToManyField(blank=True, help_text='stages picked during onboarding', related_name='interested_users', to='stages.stage'),
        ),
    ]
