# Generated by Django 5.2.6 on 2026-03-09 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_commentreaction'),
        ('posts', '0008_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'reply_to', '-created_at'], name='comments_co_post_id_1351a3_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['reply_to', 'created_at'], name='comments_co_reply_t_668f3a_idx'),
        ),
    ]
