# Generated by Django 4.1.1 on 2022-11-27 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='jusers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='stage', to=settings.AUTH_USER_MODEL),
        ),
    ]
