# Generated by Django 4.1.1 on 2022-11-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_stage_jusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='jusers',
        ),
    ]
