# Generated by Django 4.1.1 on 2022-12-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_remove_stage_jusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
