# Generated by Django 4.1.1 on 2022-12-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_alter_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
