# Generated by Django 4.2.5 on 2023-12-11 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_alter_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='stages_profile/'),
            preserve_default=False,
        ),
    ]
