# Generated by Django 5.2.6 on 2026-02-19 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_stage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stage', 'verbose_name_plural': 'Stages'},
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='date_created',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='members_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stage',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='image',
            field=models.ImageField(blank=True, help_text='Stage cover image', null=True, upload_to='stages/'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(help_text='Short unique name for URL', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(help_text='Full stage title', max_length=200),
        ),
    ]
