# Generated by Django 5.2.6 on 2026-03-06 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_alter_stage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_super_mod', models.BooleanField(default=False, help_text='Super mods can moderate every stage on the platform.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mods_added', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='stages.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_mod_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stage Moderator',
                'verbose_name_plural': 'Stage Moderators',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_issued', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_users', to='stages.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stage Ban',
                'verbose_name_plural': 'Stage Bans',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'stage')},
            },
        ),
    ]
