# Generated by Django 5.2.6 on 2026-03-07 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0008_stagemoderator_stageban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_stages', to=settings.AUTH_USER_MODEL),
        ),
    ]
