# Generated by Django 5.2.6 on 2026-03-09 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_add_members_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['is_active', '-members_count'], name='stages_stag_is_acti_b52f72_idx'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['name'], name='stages_stag_name_625878_idx'),
        ),
    ]
