# Generated by Django 5.2.6 on 2026-03-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0010_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='category',
            field=models.CharField(choices=[('general', 'Nairaland General'), ('entertainment', 'Entertainment'), ('tech', 'Science / Technology')], default='general', max_length=20),
        ),
    ]
