# Generated by Django 5.2.6 on 2026-03-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0012_populate_stage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='category',
            field=models.CharField(choices=[('general', 'Nairaland General'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('tech', 'Technology'), ('creative', 'Creative'), ('interests', 'Interests & Lifestyle')], default='general', max_length=20),
        ),
    ]
