# Generated by Django 5.2.6 on 2026-03-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0001_initial'),
        ('stages', '0008_stagemoderator_stageban'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaction',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_actions', to='stages.stage'),
        ),
        migrations.AlterField(
            model_name='modaction',
            name='action',
            field=models.CharField(choices=[('block_post', 'Block Post'), ('unblock_post', 'Unblock Post'), ('delete_post', 'Delete Post'), ('delete_comment', 'Delete Comment'), ('ban_user', 'Site Ban User'), ('unban_user', 'Site Unban User'), ('warn_user', 'Warn User'), ('dismiss_report', 'Dismiss Report'), ('resolve_report', 'Resolve Report'), ('stage_ban', 'Stage Ban User'), ('stage_unban', 'Stage Unban User'), ('add_mod', 'Add Stage Moderator'), ('remove_mod', 'Remove Stage Moderator')], max_length=20),
        ),
    ]
