# Generated by Django 5.2.6 on 2026-03-07 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_commentreaction'),
        ('moderations', '0002_modaction_stage_alter_modaction_action'),
        ('posts', '0005_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaction',
            name='action',
            field=models.CharField(choices=[('block_post', 'Block Post'), ('unblock_post', 'Unblock Post'), ('delete_post', 'Delete Post'), ('delete_comment', 'Delete Comment'), ('ban_user', 'Site Ban User'), ('unban_user', 'Site Unban User'), ('dismiss_report', 'Dismiss Report'), ('resolve_report', 'Resolve Report'), ('stage_ban', 'Stage Ban User'), ('stage_unban', 'Stage Unban User'), ('add_mod', 'Add Stage Moderator'), ('remove_mod', 'Remove Stage Moderator'), ('add_super_mod', 'Add Super Moderator'), ('remove_super_mod', 'Remove Super Moderator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='posts.post'),
        ),
    ]
