# Generated by Django 5.2.6 on 2026-03-09 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_add_performance_indexes'),
        ('moderations', '0003_report_fk_set_null_remove_warn_user'),
        ('posts', '0009_add_performance_indexes_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='moderations_status_ea979f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['post', 'status'], name='moderations_post_id_d658b4_idx'),
        ),
    ]
